### ISSUE TITLE
Add nightly CI build 

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-python#145]
https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-python

We should have a nightly build in our pipeline, similar to our other distros.

Also update ubuntu machine and collector as seen in https://github.com/honeycombio/honeycomb-opentelemetry-go/pull/151

```yaml
# circleci/config.yml
image: ubuntu-2004:2023.04.2

# smoke-tests/docker-compose.yml
image: otel/opentelemetry-collector:0.81.0
```
